# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://lampiaohacker.github.io
title: Lampião Hacker Clube
email: lampiaohacker@gmail.com
author: Lampião Hacker
description: > # "Um hackerspace é um local real com o formato de um laboratório
    comunitário que segue a ética hacker, tendo espírito agregador, convergente
    e inspirador. Nele, pessoas com interesses em comum, normalmente em ciência,
    tecnologia, arte digital ou eletrônica podem se encontrar, socializar e
    colaborar."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/lampiaohacker
  - title: github
    url: https://github.com/lampiaohacker
  - title: facebook
    url: https://www.facebook.com/groups/lampiaohacker/
